/**
 * Extrapolate the next higher and next lower values for each of multiple sequences of input values,
 * where each sequence is generated by some univariate polynomial expression.
 *
 * @see <a href="https://adventofcode.com/2023/day/9">"Day 9: Mirage Maintenance"</a>.
 */
package com.nickbenn.adventofcode.day09;
